# Generated by Django 4.2.7 on 2023-11-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
